# Generated by Django 3.2.3 on 2021-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-08-09'),
            preserve_default=False,
        ),
    ]
